// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylryskfucsbaoavnwyxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlscnlza2Z1Y3NiYW9hdm53eXh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzOTg0MjksImV4cCI6MjA3MDk3NDQyOX0.5s7O04x-xPJrpuTzvL7F16N9-HLQIvRzIlhY932a7Gc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});